; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_metro_m4]
platform = atmelsam
board = adafruit_metro_m4
framework = arduino
lib_deps = 
	waspinator/AccelStepper@^1.64
	pfeerick/elapsedMillis@^1.0.6
	koendv/RTT Stream@^1.4.1
debug_tool = jlink
upload_protocol = jlink
monitor_port = socket://localhost:19021
build_flags = -DUSE_RTT_STREAM
